version: '3'
services:
  playground:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root/.dotfiles
    stdin_open: true # docker run -i
    tty: true        # docker run -t